# base configuration for esp32c3 boards

substitutions:
  LED_GPIO: GPIO8
  BOOT_GPIO: GPIO9
  
esp32:
  variant: esp32c3
  framework:
    type: esp-idf

packages:
  - !include ./general.yaml  # general esphome settings and enable API 
  - !include ./wifi_board.yaml  # enable Wifi board prefered settings (mdns, LED, boot button, OTA, WebSever)
