# my base config for a BT proxy using esp32c3
substitutions:
  name: bluetooth-proxy
  friendly_name: BT-Proxy
  version: "26.7.0.2"
  device_description: BT-Proxy. version ${version}. Made by ErKr.
  min_version: "26.4.0"

packages:
  - !include ./common/esp32c3.yaml
  - !include ./common/btproxy.yaml
  
dashboard_import:
  package_import_url: github://erkr/esphome-device-configs/ESPHome/BT-Proxy.yaml@main
  import_full_config: false
