# BT proxy using esp32c3 with additional RTTTL support on GPIO 0
substitutions:
  name: bluetooth-proxy-rtttl
  friendly_name: BT-Proxy-rtttl
  version: "26.7.0.1"
  device_description: BT Proxy with RTTTL. v${version}. Made by ErKr.
  min_version: "26.4.0"

packages:
  - !include ./common/esp32c3.yaml
  - !include ./common/btproxy.yaml
  - !include ./common/rtttl.yaml
  
dashboard_import:
  package_import_url: github://erkr/esphome-device-configs/ESPHome/BT-Proxy-RTTTL.yaml@main
  import_full_config: false
