# my base config for a BT proxy using esp32c3
substitutions:
  name: bluetooth-test
  friendly_name: BT-Test
  version: "26.7.0.0"
  device_description: BT Test. version ${version}. Made by ErKr.

packages:
  - !import common/esp32c3.yaml
  - !import common/btproxy.yaml
  
dashboard_import:
  package_import_url: github://erkr/esphome-device-configs/ESPHome/test.yaml@main
  import_full_config: false

