# my base config for a BT proxy using esp32c3
substitutions:
  name: device-test
  friendly_name: Dev-Test
  version: "26.7.0.0"
  device_description: Dev-Test. version ${version}. Made by ErKr.
  min_version: "26.4.0"

packages:
  - !include ./common/esp32c3.yaml
  - !include ./common/btproxy.yaml
  - !include ./common/rtttl.yaml
  
dashboard_import:
  package_import_url: github://erkr/esphome-device-configs/ESPHome/test.yaml@main
  import_full_config: false
  
